services:
  - name: social-backend
    type: web
    runtime: node
    region: singapore
    repo: https://github.com/jiachwen1204-hash/social-media-platform
    branch: master
    buildCommand: cd apps/backend && npm install && npx prisma generate && npm run build
    startCommand: cd apps/backend && node dist/main.js
    envVars:
      - key: DATABASE_URL
        value: "postgresql://coffee_db_5w0e_user:nkbtRVXPsWqyeB7XUFr1WUal4hmiPYBh@dpg-d6kl09rh46gs73d0i5v0-a.singapore-postgres.render.com/coffee_db_5w0e"
