services:
  - name: social-backend
    type: web_service
    runtime: node
    region: singapore
    repo: https://github.com/jiachwen1204-hash/social-media-platform
    branch: main
    buildCommand: cd apps/backend && npm install && npx prisma generate && npm run build
    startCommand: cd apps/backend && node dist/main.js
    envVars:
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_dtR62fYjGqKa@ep-silent-math-ak0xx55v.c-3.us-west-2.aws.neon.tech/neondb?sslmode=require"
